apiVersion: apps/v1
kind: Deployment
metadata:
  name: genmcp-demo
  labels:
    app: genmcp-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: genmcp-demo
  template:
    metadata:
      labels:
        app: genmcp-demo
    spec:
      containers:
      - name: genmcp-demo
        image: ko://github.com/genmcp/gen-mcp/cmd/genmcp-server
        ports:
        - containerPort: 8080
          name: http
        env:
        - name: MCP_FILE_PATH
          value: /etc/config/mcpfile.yaml
        volumeMounts:
        - name: config
          mountPath: /etc/config
      volumes:
      - name: config
        configMap:
          name: genmcp-config
