apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    app: mcpserver
  name: mcp-genmcp-route
  namespace: default
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: mcp-genmcp-proxy
    weight: 100
  wildcardPolicy: None
